apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - name: container
     image: us.icr.io/apihub-cr/dev-pg/developer-container-utilities:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
